name: displaying message welcome
on: push
jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Welcome to Github Runner"
        
      - name: step2
        run: echo "Bye from Github Runner"

